import { useState } from 'react';
import API from '../api';

export default function FlashcardsPage() {
  const [subject, setSubject] = useState('');
  const [topic, setTopic] = useState('');
  const [flashcards, setFlashcards] = useState([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [loading, setLoading] = useState(false);
  const [mastered, setMastered] = useState(new Set());
  const [showSetup, setShowSetup] = useState(true);

  const subjects = [
    { id: 'mathematics', label: 'Mathematics', icon: '🧮' },
    { id: 'physics', label: 'Physics', icon: '🌌' },
    { id: 'computer-science', label: 'Computer Science', icon: '💻' },
    { id: 'chemistry', label: 'Chemistry', icon: '🧪' },
    { id: 'english', label: 'English', icon: '📖' },
  ];

  const topicSuggestions = {
    'mathematics': ['algebra', 'calculus', 'geometry', 'trigonometry', 'statistics', 'probability'],
    'physics': ['kinematics', 'dynamics', 'thermodynamics', 'optics', 'electromagnetism', 'quantum'],
    'computer-science': ['data-structures', 'algorithms', 'databases', 'networking', 'os', 'ai'],
    'chemistry': ['organic', 'inorganic', 'physical', 'biochemistry', 'electrochemistry'],
    'english': ['grammar', 'vocabulary', 'idioms', 'literature', 'writing'],
  };

  const generateCards = async () => {
    if (!subject || !topic) return;
    setLoading(true);
    try {
      const res = await API.post('/ai-flashcards', { subject, topic });
      if (res.data.flashcards?.length > 0) {
        setFlashcards(res.data.flashcards);
        setCurrentIdx(0);
        setFlipped(false);
        setMastered(new Set());
        setShowSetup(false);
      }
    } catch (err) { console.error(err); }
    setLoading(false);
  };

  const nextCard = () => {
    setFlipped(false);
    setTimeout(() => setCurrentIdx(prev => (prev + 1) % flashcards.length), 200);
  };

  const prevCard = () => {
    setFlipped(false);
    setTimeout(() => setCurrentIdx(prev => (prev - 1 + flashcards.length) % flashcards.length), 200);
  };

  const toggleMastered = () => {
    setMastered(prev => {
      const updated = new Set(prev);
      if (updated.has(currentIdx)) updated.delete(currentIdx);
      else updated.add(currentIdx);
      return updated;
    });
  };

  const card = flashcards[currentIdx];
  const masteredCount = mastered.size;
  const progress = flashcards.length > 0 ? (masteredCount / flashcards.length) * 100 : 0;

  if (loading) return <div className="loading-page"><div className="spinner"></div><p>AI is creating flashcards...</p></div>;

  return (
    <div className="animate-fade">
      <div className="page-header" style={{ marginBottom: 24 }}>
        <h1>🃏 AI Flashcards</h1>
        <p>Smart flashcards generated by AI for effective learning</p>
      </div>

      {showSetup ? (
        <div className="card" style={{ maxWidth: 600, margin: '0 auto', padding: 32 }}>
          <h3 style={{ fontWeight: 800, marginBottom: 24, textAlign: 'center' }}>What would you like to study?</h3>

          <div style={{ marginBottom: 24 }}>
            <label style={{ fontWeight: 600, marginBottom: 8, display: 'block' }}>Subject</label>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 12 }}>
              {subjects.map(s => (
                <button key={s.id} className={`btn ${subject === s.id ? 'btn-primary' : 'btn-secondary'} btn-sm`}
                  onClick={() => { setSubject(s.id); setTopic(''); }} style={{ borderRadius: 16 }}>
                  {s.icon} {s.label}
                </button>
              ))}
            </div>
            <input 
              className="form-input" 
              value={subject} 
              onChange={e => setSubject(e.target.value)}
              placeholder="Or type any other subject (e.g., Biology, Economics)..." 
              style={{ borderRadius: 16 }} 
            />
          </div>

          <div style={{ marginBottom: 24 }} className="animate-fade">
            <label style={{ fontWeight: 600, marginBottom: 8, display: 'block' }}>Topic</label>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 12 }}>
              {(topicSuggestions[subject] || []).map(t => (
                <button key={t} className={`btn ${topic === t ? 'btn-primary' : 'btn-ghost'} btn-sm`}
                  onClick={() => setTopic(t)} style={{ borderRadius: 16, textTransform: 'capitalize' }}>
                  {t.replace(/-/g, ' ')}
                </button>
              ))}
            </div>
            <input className="form-input" value={topic} onChange={e => setTopic(e.target.value)}
              placeholder="What specific topic? (e.g., Cellular Respiration, Demand & Supply)..." 
              style={{ borderRadius: 16 }} />
          </div>

          <button className="btn btn-primary" onClick={generateCards} disabled={!subject || !topic}
            style={{ width: '100%', borderRadius: 16, padding: '14px', fontWeight: 800 }}>
            ✨ Generate AI Flashcards
          </button>
        </div>
      ) : (
        <div>
          {/* Progress */}
          <div className="card" style={{ marginBottom: 24 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
              <span style={{ fontWeight: 600 }}>Mastery Progress</span>
              <span className="badge badge-gold">{masteredCount}/{flashcards.length} mastered</span>
            </div>
            <div className="progress-bar progress-bar-lg progress-bar-gold">
              <div className="progress-fill" style={{ width: `${progress}%` }}></div>
            </div>
          </div>

          {/* Card */}
          {card && (
            <div style={{ maxWidth: 550, margin: '0 auto', perspective: 1000 }}>
              <div onClick={() => setFlipped(!flipped)} style={{
                cursor: 'pointer', height: 300, position: 'relative',
                transformStyle: 'preserve-3d', transition: 'transform 0.6s ease',
                transform: flipped ? 'rotateY(180deg)' : 'rotateY(0)'
              }}>
                {/* Front */}
                <div className="card" style={{
                  position: 'absolute', width: '100%', height: '100%', backfaceVisibility: 'hidden',
                  display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                  padding: 32, textAlign: 'center', border: mastered.has(currentIdx) ? '2px solid var(--accent-success)' : '1px solid var(--border-color)'
                }}>
                  <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 16, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Question</div>
                  <h2 style={{ fontSize: 22, fontWeight: 700, lineHeight: 1.4 }}>{card.front}</h2>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 16 }}>Tap to flip →</div>
                </div>
                {/* Back */}
                <div className="card" style={{
                  position: 'absolute', width: '100%', height: '100%', backfaceVisibility: 'hidden',
                  transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                  padding: 32, textAlign: 'center', background: 'var(--bg-secondary)', border: '1px solid var(--accent-primary)'
                }}>
                  <div style={{ fontSize: 12, color: 'var(--accent-primary)', marginBottom: 16, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Answer</div>
                  <h2 style={{ fontSize: 20, fontWeight: 600, lineHeight: 1.5, color: 'var(--text-primary)' }}>{card.back}</h2>
                </div>
              </div>

              {/* Controls */}
              <div style={{ display: 'flex', justifyContent: 'center', gap: 12, marginTop: 24 }}>
                <button className="btn btn-secondary btn-sm" onClick={prevCard} style={{ borderRadius: 16 }}>← Prev</button>
                <button className={`btn btn-sm ${mastered.has(currentIdx) ? 'btn-primary' : 'btn-ghost'}`}
                  onClick={toggleMastered} style={{ borderRadius: 16 }}>
                  {mastered.has(currentIdx) ? '✅ Mastered' : '☐ Mark Mastered'}
                </button>
                <button className="btn btn-secondary btn-sm" onClick={nextCard} style={{ borderRadius: 16 }}>Next →</button>
              </div>

              <div style={{ textAlign: 'center', marginTop: 12, fontSize: 13, color: 'var(--text-secondary)' }}>
                Card {currentIdx + 1} of {flashcards.length} • {card.difficulty || 'medium'} difficulty
              </div>
            </div>
          )}

          {/* Actions */}
          <div style={{ display: 'flex', justifyContent: 'center', gap: 12, marginTop: 32 }}>
            <button className="btn btn-ghost" onClick={() => setShowSetup(true)} style={{ borderRadius: 16 }}>← New Topic</button>
            <button className="btn btn-secondary" onClick={generateCards} style={{ borderRadius: 16 }}>🔄 Regenerate</button>
          </div>
        </div>
      )}
    </div>
  );
}
